LOG_MODEL_INFO: False
MEMVIT:
  ENABLE: True
  ATTN_MAX_LEN: 3
  SAMPLER: gap3
  EXCLUDE_LAYERS: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47]
  COMPRESS:
    ENABLE: True
    POOL_KERNEL: [7, 3, 3]
    POOL_STRIDE: [4, 2, 2]
TRAIN:
  DATASET: ava
  BATCH_SIZE: 16
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: models/Kinetics/MeMViT_24L_32x3_K600.pyth
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_EPOCH_RESET: True
MODEL:
  ARCH: mvit
  MODEL_NAME: MViT
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  NUM_CLASSES: 80
  HEAD_ACT: sigmoid
DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: torchvision
  NUM_FRAMES: 32
  SAMPLING_RATE: 3
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]

  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  PERTURB_AVA_FRAMES: True
MVIT:
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: [3, 7, 7]
  PATCH_STRIDE: [2, 4, 4]
  PATCH_PADDING: [1, 3, 3]
  ZERO_DECAY_POS_CLS: False
  QKV_BIAS: True

  DEPTH: 24
  DIM_MUL: [[2, 2.0], [5, 2.0], [21, 2.0]]
  HEAD_MUL: [[2, 2.0], [5, 2.0], [21, 2.0]]

  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 1, 1], [2, 1, 2, 2], [3, 1, 1, 1], [4, 1, 1, 1], [5, 1, 2, 2], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1],
  [11, 1, 1, 1], [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 1, 1], [15, 1, 1, 1], [16, 1, 1, 1], [17, 1, 1, 1], [18, 1, 1, 1], [19, 1, 1, 1], [20, 1, 1, 1],
  [21, 1, 2, 2], [22, 1, 1, 1], [23, 1, 1, 1] ]

  DROPPATH_RATE: 0.4

  USE_ABS_POS: False
  REL_POS_SPATIAL: True
  REL_POS_TEMPORAL: True
  CONV_Q: 1
  MODE: "conv"

  POOL_FIRST: True
  DIM_MUL_IN_ATT: True
  POOL_KVQ_KERNEL: [3, 3, 3]

  BOX_DEPTH: 1
  BOX_DROP_ATTN_RATE: 0.5
  BOX_DROP_QKV_RATE: 0.3
  BOX_DROPOUT_RATE: 0.3

DETECTION:
  ENABLE: True
  ALIGNED: True
  SPATIAL_SCALE_FACTOR: 32
AVA:
  BGR: False
  DETECTION_SCORE_THRESH: 0.9
  TRAIN_PREDICT_BOX_LISTS: [
    "ava_train_v2.2.csv",
    "person_box_67091280_iou90/ava_detection_train_boxes_and_labels_include_negative_v2.2.csv",
  ]
  TEST_PREDICT_BOX_LISTS: ["data/ava/person_box_67091280_iou90/ava_detection_val_boxes_and_labels.csv"]
  ANNOTATION_DIR: "data/ava/frame_list"
  FRAME_LIST_DIR: "data/ava/frame_list"
  FRAME_DIR: "data/ava/ava_trainval_frames"
  FULL_TEST_ON_VAL: True
SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.075
  CLIP_GRAD_L2NORM: 5.0
  LR_POLICY: cosine
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  MAX_EPOCH: 40
  WARMUP_EPOCHS: 6.0
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-8
  ZERO_WD_1D_PARAM: True
  WARMUP_START_LR: 0.000001
  OPTIMIZING_METHOD: sgd
TEST:
  ENABLE: True
  DATASET: ava
  NUM_SPATIAL_CROPS: 1
  BATCH_SIZE: 8
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 16
RNG_SEED: 0
OUTPUT_DIR: .
